# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/kaytu-io/kaytu"
  version "0.12.5"

  on_macos do
    on_intel do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.5/kaytu_0.12.5_darwin_amd64.tar.gz"
      sha256 "bb26ca91105ce1eb73d6790aae5be9c2d28794ee739ce0f6c57abd1a31f2b9da"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.5/kaytu_0.12.5_darwin_arm64.tar.gz"
      sha256 "4c6fb039386e4dcc6d831d266785c42dcbc285d22849b0c23edd38e0fef7da4d"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.5/kaytu_0.12.5_linux_amd64.tar.gz"
        sha256 "a71e2af5cdc0fbcdda4cdd8d30ceb84e7db13e8241f7bce5bf240384bef029da"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.5/kaytu_0.12.5_linux_arm64.tar.gz"
        sha256 "e9766d0fe56fc84594544ed6a4da4c0aced9ab48281b5799659008becc0c1808"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
