# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/kaytu-io/kaytu"
  version "0.14.1"

  on_macos do
    on_intel do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.14.1/kaytu_0.14.1_darwin_amd64.tar.gz"
      sha256 "fde4dfa75cc691f6359b2aeeadd29bb9520d26beb313da6a79ca1b6832869ed0"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.14.1/kaytu_0.14.1_darwin_arm64.tar.gz"
      sha256 "29bf4463ed68c4afee5852bbd118d4ecdba48438d19c4546a7fa623b663bd7dd"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.14.1/kaytu_0.14.1_linux_amd64.tar.gz"
        sha256 "a5d89df6652cd13a6d30b3e40a87f850ea07af0eafe9f24971de4a2090f6e7be"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.14.1/kaytu_0.14.1_linux_arm64.tar.gz"
        sha256 "389267108c1c20ad1b4cc7fade830a2755b0781895130f3545ad7333dbfdf56a"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
