# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaytu < Formula
  desc ""
  homepage "https://github.com/kaytu-io/kaytu"
  version "0.12.9"

  on_macos do
    on_intel do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.9/kaytu_0.12.9_darwin_amd64.tar.gz"
      sha256 "1d6a433a3939f341c0ccd2361ca447ff218c6158efecd61a8dbe4cf026620d3a"

      def install
        bin.install "kaytu"
      end
    end
    on_arm do
      url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.9/kaytu_0.12.9_darwin_arm64.tar.gz"
      sha256 "ff27e9779518de734533bfb5d6ccd2b819d45316ec12fa8acc2910977af79e81"

      def install
        bin.install "kaytu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.9/kaytu_0.12.9_linux_amd64.tar.gz"
        sha256 "83217b0b19b1d3b4b06f2ca55d48599670d6564e8f15631de712d741159a2ec8"

        def install
          bin.install "kaytu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kaytu-io/kaytu/releases/download/v0.12.9/kaytu_0.12.9_linux_arm64.tar.gz"
        sha256 "04d0be23bcfc33c1aa064d2d764ab23a7326d584735bb9a1c7793c6002361f2d"

        def install
          bin.install "kaytu"
        end
      end
    end
  end
end
